### ISSUE TITLE
Operation access speed

### ISSUE THREAD

**Issue by TanaTanoi** [dylanmckay/rails-euchre#10]
the `operations` method in `game.rb` gets slower as the size of `operations` increases, I recommend using queries rather than ruby iterators

**Comment by dylanmckay** [comment]
The log of `rails server` shows a very large number of `SELECT * FROM players WHERE ID=<id here>` queries.

**Comment by TanaTanoi** [comment]
Closed with 741cb67d11a618fce30647eae35342ba20b08cf2
